language: cpp
dist: trusty
sudo: true

branches:
  only:
    - master
    - working


matrix:
  include:

    - os: linux
      compiler:
        - clang
      env:
        - TEST="Clang"
      addons:
        apt:
          packages:
      script:
        - cmake CMakeLists.txt
        - make
        - make IZ1



after_success:
  - bash <(curl -s https://codecov.io/bash)