
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: clang
      addons:
        apt:
          packages: &precise_latest_boost_packages
            - valgrind
            - python-yaml
            - lcov
            - libopencv-dev
          sources: &precise_latest_boost_sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7


install:
  - sudo pip install codecov



script:
  - cmake CMakeLists.txt
  - make
  - make IZ1
  - ctest
after_success:
  - codecov -t 97178361-a3d8-4f0e-a1aa-8f4154931fd6 -X gcov