language: cpp
dist: trusty
sudo: true

branches:
  only:
    - master
    - working


matrix:
  include:

    - os: linux
      compiler:
        - clang
      env:
        - TEST="Clang"
      script:
        - cmake CMakeLists.txt
        - make
        - make IZ1

    - os: linux
      compiler:
        - g++
      env:
        - TEST="Gcc"
      script:
        - cmake CMakeLists.txt
        - make
        - make IZ1

    - os: linux
      compiler:
        - clang
      env:
        - TEST="UnitTest"
      script:
        - cmake CMakeLists.txt
        - make
        - ctest



after_success:
  - bash <(curl -s https://codecov.io/bash)